add_newline = true
palette = "dracula"
command_timeout = 200

# ---------- PROMPT LAYOUT ----------
format = """
$directory\
$git_branch$git_status\
$nodejs$python$cmd_duration
$character
"""

# ---------- CHARACTER ----------
[character]
success_symbol = "[󰜴](bold green)"
error_symbol = "[󰜴](bold red)"

# ---------- DIRECTORY ----------
[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
read_only = " "

# ---------- GIT ----------
[git_branch]
format = " [ $branch]($style)"
style = "bold pink"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "bold yellow"

ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = " ✖"
untracked = " ?"
modified = " ●"
staged = " ✔"
renamed = " ➜"
deleted = " ✘"
stashed = " ≡"

# ---------- LANGUAGES ----------
[nodejs]
format = " [ $version](bold green)"

[python]
format = " [ $version](bold blue)"

# ---------- CMD DURATION ----------
# [cmd_duration]
# min_time = 500
# format = " [⏱ $duration](italic yellow)"

# ---------- OPTIONAL CLEANUPS ----------
[username]
disabled = true

[hostname]
disabled = true

# ---------- PALETTE ----------
[palettes.dracula]
background = "#282a36"
foreground = "#f8f8f2"
pink = "#ff79c6"
red = "#ff5555"
green = "#50FA7B"
yellow = "#f1fa8c"
blue = "#88B3FA"
cyan = "#8be9fd"
