add_newline = true
palette = "dracula"
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[ ](bold red)"
success_symbol = "[ ](bold blue)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic red"

[git_status]
format = '[$all_status]($style)'
style = "bold green"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = " "
staged = " "
renamed = "󰑕 "
deleted = " "

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
pink = "#ff79c6"
red = "#ff5555"
green = "#50FA7B"
blue = "#88B3FA"
