
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$nodejs\
$python\
$time\n  \
[󱞪](fg:iris) \
"""

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#ff79c6'
gold = '#ff5555'
rose = '#50fa7b'
pine = '#f1fa8c'
foam = '#88b3fa'
iris = '#8be9fd'

[os]
format = "[](fg:overlay)[ $symbol ]($style)"
style = "bg:overlay fg:foam"
disabled = false

[os.symbols]
Arch = "󰣇"

[shell]
format = "[ $indicator ]($style)[](fg:overlay) "
fish_indicator = "󰈺"
style = "bg:overlay fg:rose"
disabled = false

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""

# [git_commit]
# format = "[](fg:overlay)[ 󰜘 $hash ]($style)[](fg:overlay) "
# style = "bg:overlay fg:foam"
# tag_symbol = " 󰓼 "
# only_detached = false
#
[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ 󰄭 ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:rose)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[time]
disabled = true
format = " [](fg:overlay)[ $time  ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true


[username]
disabled = true
format = "[](fg:overlay)[   $user ]($style)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

[hostname]
ssh_only = false
ssh_symbol = "󱓞 "
format = "[](fg:overlay)[ $ssh_symbol $hostname ]($style)[](fg:overlay) "
style = "bg:overlay fg:iris"
disabled = true

# Languages

[c]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = true
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰎙 "

[python]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = ' '


