 windowrule = opacity 0.95 0.95,match:class ^(kitty)$
 windowrule = opacity 1.0 1.0,match:class ^(org\.gnome\.Nautilus)$
 windowrule = opacity 1.0 1.0,match:class ^(zen)$
#windowrule = opacity 1.0 1.0,match:class .*

windowrule = float 1, size 1050 700, move cursor, match:class ^(org\.gnome\.Nautilus)$
#windowrule = float 1, size 1000 700, move cursor, match:class ^(kitty)$
#windowrule = float 1, size 1000 700, move cursor, match:class ^(Alacritty)$
#windowrule = float 1, size 1400 900, move cursor, match:class ^(com\.github\.PintaProject\.Pinta)$
windowrule = float 1, size 1300 850, move cursor, match:class ^(obsidian|Obsidian)$
windowrule = float 1, size 1350 850, move cursor, match:class ^(vlc|Vlc)$
windowrule = float 1, size 1150 800, move cursor, match:class ^(firefox)$
windowrule = float 1, size 1150 800, move cursor, match:class ^(zen)$
