

# ==========================================
# Minimal Black Borders
# ==========================================

$activeBorderColor = rgb(189,147,249)        # Pure black
$inactiveBorderColor = rgb(20,20,20)   # Soft charcoal

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

