#binding r for reloading
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"
#binding control-s as leader key 
set -g prefix C-s
set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on
##### Mouse support #####
set -g mouse on
#set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-position top
set -g status-interval 3
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g set-clipboard on
##### Splits #####
bind | split-window -h   # Horizontal split
bind - split-window -v   # Vertical split

##### Vim-Tmux-Navigator integration #####
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE 'n?vim'"

bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

##### Pane resizing with Alt + h j k l #####

bind -n M-h resize-pane -L 5
bind -n M-l resize-pane -R 5
bind -n M-j resize-pane -D 5
bind -n M-k resize-pane -U 5

setw -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
bind-key -T copy-mode-vi r send -X rectangle-toggle


thm_bg="#000000"
thm_fg="#a9b1d6"
thm_cyan="#449dab"
thm_black="#32344a"
thm_gray="#444b6a"
thm_magenta="#ad8ee6"
thm_pink="#ad8ee6"
thm_red="#f7768e"
thm_green="#9ece6a"
thm_yellow="#e0af68"
thm_blue="#7aa2f7"
thm_orange="#e0af68"
thm_black4="#32344a"
# Status bar
set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

# Statusline - current window
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_magenta},bg=${thm_bg}](✓) #[fg=${thm_cyan},bg=${thm_bg}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_magenta},bg=${thm_bg}]"

# Statusline - other windows
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_fg},bg=${thm_bg}]#W"

# Statusline - right side
set -g status-right "#[fg=${thm_blue},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_blue},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_gray}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_gray}] #S "

# Statusline - left side (empty)
set -g status-left ""

# Modes
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"

